[project]
name = "notamproj"
version = "0.1.5"
description = "notamp plotter project"
authors = [
    {name = "JelmerKorten"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "curl-cffi==0.16.0",
    "pandas==2.3.0",
    "plotly==6.1.2",
    "pyproj==3.7.1",
    "python-dotenv==1.0.1",
    "PyYAML==6.0.2",
    "shapely==2.1.1"
]

[project.scripts]
notamplotter = "notamplotter.cli:main"

[project.optional-dependencies]
dev = [
    "pytest==8.3.5",
    "ruff==0.12.0"
]


[tool.ruff]
line-length = 120
target-version = "py313"
exclude = ["deprecated"]


[tool.poetry]
packages = [{ include = "notamplotter" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
