name: Manual-Workflow

on:
  workflow_dispatch
  inputs:
    var_x:
      description: 'var_x input'
      required: true
      default: 'default value for var_x'
    var_y:
      description: 'var_y description'

  jobs:

    build:
      name: Create windows binary
      runs-on: windows-latest

      steps:
        - name: print
          run: echo "Olaa"
        - name: create env
          run: somehow create env here?
        - name: create package
          run: python setup.py build
        
